export const INDEXABILITY_RULE_IDS = {

    // HTTP
    INDEX_001_FETCH_FAILED: "INDEX_001_FETCH_FAILED",
    INDEX_002_404_STATUS: "INDEX_002_404_STATUS",
    INDEX_003_5XX_STATUS: "INDEX_003_5XX_STATUS",
    INDEX_004_SOFT_404: "INDEX_004_SOFT_404",

    // Redirect
    INDEX_005_REDIRECT_CHAIN: "INDEX_005_REDIRECT_CHAIN",
    INDEX_006_REDIRECT_LOOP: "INDEX_006_REDIRECT_LOOP",
    INDEX_007_TOO_MANY_REDIRECTS: "INDEX_007_TOO_MANY_REDIRECTS",

    // Robots directives
    INDEX_008_NOINDEX: "INDEX_008_NOINDEX",
    INDEX_009_X_ROBOTS_NOINDEX: "INDEX_009_X_ROBOTS_NOINDEX",

    // Canonical
    INDEX_010_CANONICAL_CONFLICT: "INDEX_010_CANONICAL_CONFLICT",
    INDEX_011_CANONICAL_TO_ERROR: "INDEX_011_CANONICAL_TO_ERROR",
    INDEX_012_CANONICAL_TO_NOINDEX: "INDEX_012_CANONICAL_TO_NOINDEX",

    // Sitemap
    INDEX_013_SITEMAP_NOINDEX_CONFLICT:
        "INDEX_013_SITEMAP_NOINDEX_CONFLICT",

    // Rendering
    INDEX_014_CONTENT_REQUIRES_JAVASCRIPT:
        "INDEX_014_CONTENT_REQUIRES_JAVASCRIPT",

    INDEX_015_BLOCKED_JAVASCRIPT_RESOURCES:
        "INDEX_015_BLOCKED_JAVASCRIPT_RESOURCES",


} as const;

export type indexabilityRuleId =
    typeof INDEXABILITY_RULE_IDS[keyof typeof INDEXABILITY_RULE_IDS];