export const CRAWLABILITY_RULE_IDS = {

    // Fetch
    CRAWL_001_FETCH_FAILED: "CRAWL_001_FETCH_FAILED",
    CRAWL_002_5XX_STATUS: "CRAWL_002_5XX_STATUS",
    CRAWL_003_429_STATUS: "CRAWL_003_429_STATUS",

    // Robots
    CRAWL_004_ROBOTS_BLOCKED: "CRAWL_004_ROBOTS_BLOCKED",

    // Discovery
    CRAWL_005_NOT_IN_SITEMAP: "CRAWL_005_NOT_IN_SITEMAP",
    CRAWL_006_NOT_DISCOVERED_VIA_SITEMAP:
        "CRAWL_006_NOT_DISCOVERED_VIA_SITEMAP",
    CRAWL_007_NOT_DISCOVERED_VIA_INTERNAL_LINK:
        "CRAWL_007_NOT_DISCOVERED_VIA_INTERNAL_LINK",
    CRAWL_008_ORPHAN_PAGE: "CRAWL_008_ORPHAN_PAGE",
    CRAWL_009_LOW_INTERNAL_INCOMING_LINKS:
        "CRAWL_009_LOW_INTERNAL_INCOMING_LINKS",

    // Crawl depth
    CRAWL_010_EXCESSIVE_CRAWL_DEPTH:
        "CRAWL_010_EXCESSIVE_CRAWL_DEPTH",
    CRAWL_011_EXCESSIVE_URL_DEPTH:
        "CRAWL_011_EXCESSIVE_URL_DEPTH",

    // URL
    CRAWL_012_LONG_URL: "CRAWL_012_LONG_URL",
    CRAWL_013_EXCESSIVE_QUERY_PARAMETERS:
        "CRAWL_013_EXCESSIVE_QUERY_PARAMETERS",
    CRAWL_014_SESSION_ID_IN_URL:
        "CRAWL_014_SESSION_ID_IN_URL",
    CRAWL_015_TRACKING_PARAMETER_IN_URL:
        "CRAWL_015_TRACKING_PARAMETER_IN_URL",

} as const;

export type crawlabilityRuleId =
    typeof CRAWLABILITY_RULE_IDS[keyof typeof CRAWLABILITY_RULE_IDS];